"""Renogy tests consts."""

CONFIG_DATA = {
    "name": "Renogy Core",
    "secret_key": "fakeRandomSecretKey",
    "access_key": "fakeRandomAccessKey",
}

DIAG_RESULTS = {
    "1234567890": {
        "connection": "Hub",
        "data": {},
        "deviceId": "1234567890",
        "firmware": "V1.1.157",
        "mac": "DE:AD:BE:EF:FE:ED",
        "model": "RSHGWSN-W02W-G1",
        "name": "Renogy ONE Core",
        "serial": "TOTALLYFAKESN",
        "status": "online",
    },
    "12345678901": {
        "connection": "RS485",
        "data": {
            "acOutputHz": 60.0,
            "auxiliaryBatteryTemperature": None,
            "batteryType": None,
            "batteryVolts": 12.6,
            "chargePriority": None,
            "loadActiveWatts": 42,
            "loadAmps": None,
            "loadWatts": None,
            "loadWattsMode": None,
            "output": 1,
            "outputAmps": 370.0,
            "outputVolts": 114.099998,
            "sku": "RINVTPGH110111S",
            "solarChargingAmps": None,
            "solarChargingVolts": None,
            "solarWatts": None,
            "temperature": 22.0,
            "ueiAmps": None,
            "ueiVolts": None,
        },
        "deviceId": "12345678901",
        "firmware": "0100.0102.0202",
        "mac": "32",
        "model": "RINVTPGH110111S",
        "name": "Inverter",
        "serial": "",
        "status": "online",
    },
    "12345678902": {
        "connection": "Bluetooth",
        "data": {
            "auxiliaryBatteryChargingVolts": 14.4,
            "auxiliaryBatteryChargingWatts": None,
            "auxiliaryBatteryTemperature": 2.0,
            "batteryType": 4,
            "gridChargeAmps": 0.0,
            "loadAmps": 0.0,
            "loadVolts": 0.0,
            "loadWatts": 0,
            "sku": "RNG-CTRL-RVR40",
            "soc": 100,
            "solarChargingAmps": 0.0,
            "solarChargingVolts": 15.3,
            "solarWatts": 0.0,
            "status": None,
            "systemVolts": 12,
            "totalKwhGenerated": 449358.03125,
        },
        "deviceId": "12345678902",
        "firmware": "",
        "mac": "F0:F8:F2:5D:5D:8716",
        "model": "RNG-CTRL-RVR40",
        "name": "RNG-CTRL-RVR40",
        "serial": "",
        "status": "online",
    },
    "12345678903": {
        "connection": "RS485",
        "data": {
            "averageTemperature": -3,
            "batteryLevel": 54.784637,
            "heatingModeStatus": 0,
            "maximumCapacity": 99.505997,
            "presentAmps": 0.0,
            "presentCapacity": 54.518002,
            "presentVolts": 13.0,
            "sku": "RBT100LFP12SH-G1",
        },
        "deviceId": "12345678903",
        "firmware": "",
        "mac": "48",
        "model": "RBT100LFP12SH-G1",
        "name": "RBT100LFP12SH-G1",
        "serial": "",
        "status": "online",
    },
}
